// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book/book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	user "github.com/y-zumi/grpc-go/proto/user"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindLendingBookByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLendingBookByIDRequest) Reset()         { *m = FindLendingBookByIDRequest{} }
func (m *FindLendingBookByIDRequest) String() string { return proto.CompactTextString(m) }
func (*FindLendingBookByIDRequest) ProtoMessage()    {}
func (*FindLendingBookByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{0}
}

func (m *FindLendingBookByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLendingBookByIDRequest.Unmarshal(m, b)
}
func (m *FindLendingBookByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLendingBookByIDRequest.Marshal(b, m, deterministic)
}
func (m *FindLendingBookByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLendingBookByIDRequest.Merge(m, src)
}
func (m *FindLendingBookByIDRequest) XXX_Size() int {
	return xxx_messageInfo_FindLendingBookByIDRequest.Size(m)
}
func (m *FindLendingBookByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLendingBookByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLendingBookByIDRequest proto.InternalMessageInfo

func (m *FindLendingBookByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindLendingBookByIDResponse struct {
	Book                 *Book      `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Borrower             *user.User `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindLendingBookByIDResponse) Reset()         { *m = FindLendingBookByIDResponse{} }
func (m *FindLendingBookByIDResponse) String() string { return proto.CompactTextString(m) }
func (*FindLendingBookByIDResponse) ProtoMessage()    {}
func (*FindLendingBookByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{1}
}

func (m *FindLendingBookByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLendingBookByIDResponse.Unmarshal(m, b)
}
func (m *FindLendingBookByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLendingBookByIDResponse.Marshal(b, m, deterministic)
}
func (m *FindLendingBookByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLendingBookByIDResponse.Merge(m, src)
}
func (m *FindLendingBookByIDResponse) XXX_Size() int {
	return xxx_messageInfo_FindLendingBookByIDResponse.Size(m)
}
func (m *FindLendingBookByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLendingBookByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLendingBookByIDResponse proto.InternalMessageInfo

func (m *FindLendingBookByIDResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *FindLendingBookByIDResponse) GetBorrower() *user.User {
	if m != nil {
		return m.Borrower
	}
	return nil
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*FindLendingBookByIDRequest)(nil), "book.FindLendingBookByIDRequest")
	proto.RegisterType((*FindLendingBookByIDResponse)(nil), "book.FindLendingBookByIDResponse")
	proto.RegisterType((*Book)(nil), "book.Book")
}

func init() { proto.RegisterFile("proto/book/book.proto", fileDescriptor_98814f1514a537b6) }

var fileDescriptor_98814f1514a537b6 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xb1, 0x2d, 0x76, 0x04, 0x0f, 0xeb, 0x07, 0x21, 0x82, 0xd4, 0x20, 0xc5, 0x83, 0x4d,
	0xa0, 0xfe, 0x83, 0x50, 0x04, 0xc1, 0xd3, 0x82, 0x97, 0xde, 0x4c, 0x32, 0xc4, 0xa5, 0x36, 0x13,
	0x77, 0x76, 0x91, 0xfa, 0xeb, 0x25, 0x93, 0xa0, 0x20, 0xb1, 0x97, 0x61, 0xde, 0xbc, 0xf7, 0x76,
	0xde, 0xb0, 0x70, 0xd1, 0x58, 0x72, 0x94, 0xe6, 0x44, 0x5b, 0x29, 0x89, 0x60, 0x35, 0x6e, 0xfb,
	0xa8, 0x27, 0x3d, 0xa3, 0x95, 0xd2, 0x91, 0xf1, 0x3d, 0x44, 0x8f, 0xa6, 0x2e, 0x9f, 0xb1, 0x2e,
	0x4d, 0x5d, 0x65, 0x44, 0xdb, 0x6c, 0xff, 0xb4, 0xd6, 0xf8, 0xe1, 0x91, 0x9d, 0x3a, 0x85, 0xc0,
	0x94, 0xe1, 0x68, 0x3e, 0xba, 0x9b, 0xe9, 0xc0, 0x94, 0x31, 0xc2, 0xd5, 0xa0, 0x9a, 0x1b, 0xaa,
	0x19, 0xd5, 0x35, 0xc8, 0x2e, 0x31, 0x9c, 0xac, 0x20, 0x91, 0x10, 0xad, 0x4a, 0xcb, 0x5c, 0x2d,
	0xe0, 0x38, 0x27, 0x6b, 0xe9, 0x13, 0x6d, 0x18, 0xf4, 0x1a, 0xc9, 0xf2, 0xc2, 0x68, 0xf5, 0x0f,
	0x17, 0xaf, 0x61, 0xdc, 0xba, 0xfe, 0xae, 0x57, 0xe7, 0x30, 0x71, 0xc6, 0xbd, 0xa3, 0x98, 0x67,
	0xba, 0x03, 0xea, 0x12, 0xa6, 0xec, 0x5e, 0x9d, 0xe7, 0xf0, 0x48, 0xc6, 0x3d, 0x5a, 0x15, 0x30,
	0x69, 0x5f, 0x61, 0xb5, 0x81, 0xb3, 0x81, 0xd4, 0x6a, 0xde, 0xe5, 0xfb, 0xff, 0xfc, 0xe8, 0xe6,
	0x80, 0xa2, 0x3b, 0x39, 0x5b, 0x6c, 0x6e, 0x2b, 0xe3, 0xde, 0x7c, 0x9e, 0x14, 0xb4, 0x4b, 0xf7,
	0xcb, 0x2f, 0xbf, 0x33, 0x69, 0x65, 0x9b, 0x62, 0x59, 0x51, 0xfa, 0xfb, 0x1f, 0xf9, 0x54, 0xfa,
	0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x3c, 0x83, 0xa5, 0xa4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BooksClient is the client API for Books service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BooksClient interface {
	FindLendingBookByID(ctx context.Context, in *FindLendingBookByIDRequest, opts ...grpc.CallOption) (*FindLendingBookByIDResponse, error)
}

type booksClient struct {
	cc *grpc.ClientConn
}

func NewBooksClient(cc *grpc.ClientConn) BooksClient {
	return &booksClient{cc}
}

func (c *booksClient) FindLendingBookByID(ctx context.Context, in *FindLendingBookByIDRequest, opts ...grpc.CallOption) (*FindLendingBookByIDResponse, error) {
	out := new(FindLendingBookByIDResponse)
	err := c.cc.Invoke(ctx, "/book.Books/FindLendingBookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServer is the server API for Books service.
type BooksServer interface {
	FindLendingBookByID(context.Context, *FindLendingBookByIDRequest) (*FindLendingBookByIDResponse, error)
}

// UnimplementedBooksServer can be embedded to have forward compatible implementations.
type UnimplementedBooksServer struct {
}

func (*UnimplementedBooksServer) FindLendingBookByID(ctx context.Context, req *FindLendingBookByIDRequest) (*FindLendingBookByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLendingBookByID not implemented")
}

func RegisterBooksServer(s *grpc.Server, srv BooksServer) {
	s.RegisterService(&_Books_serviceDesc, srv)
}

func _Books_FindLendingBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLendingBookByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).FindLendingBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Books/FindLendingBookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).FindLendingBookByID(ctx, req.(*FindLendingBookByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Books_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.Books",
	HandlerType: (*BooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindLendingBookByID",
			Handler:    _Books_FindLendingBookByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/book/book.proto",
}
