// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book/book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	user "github.com/y-zumi/grpc-go/proto/user"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindLendingBookByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLendingBookByIDRequest) Reset()         { *m = FindLendingBookByIDRequest{} }
func (m *FindLendingBookByIDRequest) String() string { return proto.CompactTextString(m) }
func (*FindLendingBookByIDRequest) ProtoMessage()    {}
func (*FindLendingBookByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{0}
}

func (m *FindLendingBookByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLendingBookByIDRequest.Unmarshal(m, b)
}
func (m *FindLendingBookByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLendingBookByIDRequest.Marshal(b, m, deterministic)
}
func (m *FindLendingBookByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLendingBookByIDRequest.Merge(m, src)
}
func (m *FindLendingBookByIDRequest) XXX_Size() int {
	return xxx_messageInfo_FindLendingBookByIDRequest.Size(m)
}
func (m *FindLendingBookByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLendingBookByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLendingBookByIDRequest proto.InternalMessageInfo

func (m *FindLendingBookByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindLendingBookByIDResponse struct {
	Book                 *Book      `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Borrower             *user.User `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindLendingBookByIDResponse) Reset()         { *m = FindLendingBookByIDResponse{} }
func (m *FindLendingBookByIDResponse) String() string { return proto.CompactTextString(m) }
func (*FindLendingBookByIDResponse) ProtoMessage()    {}
func (*FindLendingBookByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{1}
}

func (m *FindLendingBookByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLendingBookByIDResponse.Unmarshal(m, b)
}
func (m *FindLendingBookByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLendingBookByIDResponse.Marshal(b, m, deterministic)
}
func (m *FindLendingBookByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLendingBookByIDResponse.Merge(m, src)
}
func (m *FindLendingBookByIDResponse) XXX_Size() int {
	return xxx_messageInfo_FindLendingBookByIDResponse.Size(m)
}
func (m *FindLendingBookByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLendingBookByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLendingBookByIDResponse proto.InternalMessageInfo

func (m *FindLendingBookByIDResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *FindLendingBookByIDResponse) GetBorrower() *user.User {
	if m != nil {
		return m.Borrower
	}
	return nil
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_98814f1514a537b6, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*FindLendingBookByIDRequest)(nil), "book.FindLendingBookByIDRequest")
	proto.RegisterType((*FindLendingBookByIDResponse)(nil), "book.FindLendingBookByIDResponse")
	proto.RegisterType((*Book)(nil), "book.Book")
}

func init() { proto.RegisterFile("proto/book/book.proto", fileDescriptor_98814f1514a537b6) }

var fileDescriptor_98814f1514a537b6 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xb1, 0x16, 0x3b, 0x05, 0x0f, 0xeb, 0x07, 0x21, 0x82, 0xd4, 0x20, 0xc5, 0x83, 0x4d,
	0xa0, 0xfe, 0x83, 0x50, 0x04, 0xc1, 0xd3, 0x8a, 0x97, 0xde, 0x4c, 0x32, 0xc4, 0xa1, 0x36, 0x13,
	0xf7, 0x43, 0xa9, 0xbf, 0x5e, 0x32, 0x09, 0x0a, 0x52, 0x7b, 0x19, 0xe6, 0xcd, 0x7b, 0x6f, 0xe7,
	0xed, 0x2e, 0x9c, 0x35, 0x86, 0x1d, 0xa7, 0x39, 0xf3, 0x5a, 0x4a, 0x22, 0x58, 0x0d, 0xdb, 0x3e,
	0xea, 0x49, 0x6f, 0xd1, 0x48, 0xe9, 0xc8, 0xf8, 0x16, 0xa2, 0x7b, 0xaa, 0xcb, 0x47, 0xac, 0x4b,
	0xaa, 0xab, 0x8c, 0x79, 0x9d, 0x6d, 0x1f, 0x96, 0x1a, 0xdf, 0x3d, 0x5a, 0xa7, 0x8e, 0x21, 0xa0,
	0x32, 0x1c, 0x4c, 0x07, 0x37, 0x63, 0x1d, 0x50, 0x19, 0x23, 0x5c, 0xec, 0x54, 0xdb, 0x86, 0x6b,
	0x8b, 0xea, 0x12, 0x64, 0x97, 0x18, 0x26, 0x0b, 0x48, 0x24, 0x44, 0xab, 0xd2, 0x32, 0x57, 0x33,
	0x38, 0xca, 0xd9, 0x18, 0xfe, 0x44, 0x13, 0x06, 0xbd, 0x46, 0xb2, 0x3c, 0x5b, 0x34, 0xfa, 0x87,
	0x8b, 0x97, 0x30, 0x6c, 0x5d, 0x7f, 0xd7, 0xab, 0x53, 0x38, 0x74, 0xe4, 0xde, 0x50, 0xcc, 0x63,
	0xdd, 0x01, 0x75, 0x0e, 0x23, 0xeb, 0x5e, 0x9c, 0xb7, 0xe1, 0x81, 0x8c, 0x7b, 0xb4, 0x20, 0x98,
	0xb4, 0xa7, 0x3c, 0xa1, 0xf9, 0xa0, 0x02, 0xd5, 0x0a, 0x4e, 0x76, 0x64, 0x57, 0xd3, 0x2e, 0xe5,
	0xff, 0x8f, 0x10, 0x5d, 0xed, 0x51, 0x74, 0x17, 0xcf, 0x66, 0xab, 0xeb, 0x8a, 0xdc, 0xab, 0xcf,
	0x93, 0x82, 0x37, 0xe9, 0x76, 0xfe, 0xe5, 0x37, 0x94, 0x56, 0xa6, 0x29, 0xe6, 0x15, 0xa7, 0xbf,
	0xbf, 0x92, 0x8f, 0xa4, 0xbf, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xf7, 0xb3, 0x53, 0xaa,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	FindLendingBookByID(ctx context.Context, in *FindLendingBookByIDRequest, opts ...grpc.CallOption) (*FindLendingBookByIDResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) FindLendingBookByID(ctx context.Context, in *FindLendingBookByIDRequest, opts ...grpc.CallOption) (*FindLendingBookByIDResponse, error) {
	out := new(FindLendingBookByIDResponse)
	err := c.cc.Invoke(ctx, "/book.BookService/FindLendingBookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	FindLendingBookByID(context.Context, *FindLendingBookByIDRequest) (*FindLendingBookByIDResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) FindLendingBookByID(ctx context.Context, req *FindLendingBookByIDRequest) (*FindLendingBookByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLendingBookByID not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_FindLendingBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLendingBookByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).FindLendingBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/FindLendingBookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).FindLendingBookByID(ctx, req.(*FindLendingBookByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindLendingBookByID",
			Handler:    _BookService_FindLendingBookByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/book/book.proto",
}
